#!/bin/sh
gdb --args opp_run -l../../base/miximbase -l../../modules/miximmodules -l../../inet4mixnet/src/inet -l../../inet/src/mixnet -n../../base:../../modules:../../inet/src:../../inet4mixnet/src:.. "$@"
