#!/bin/sh
valgrind --tool=memcheck --leak-check=full --dsymutil=yes --log-file=valgrind.out -- opp_run -l../../base/miximbase -l../../modules/miximmodules -l../../inet4mixnet/src/inet -l../../inet/src/mixnet -n../../base:../../modules:../../inet/src:../../inet4mixnet/src:.. "$@"
